import type { Grant } from './types';

export const GRANTS_DATA: Grant[] = [
    {
        id: 'g-001',
        name: 'VWO Capability Fund',
        agency: 'NCSS',
        description: 'Provides funding for VWOs to strengthen their governance and management capabilities.',
        quantum: 'Up to $100,000',
        deadline: '2026-06-30',
        sectors: ['Social Service', 'Health', 'Community'],
        eligibility: ['Registered Charity', 'IPC Status', 'Member of NCSS'],
    },
    {
        id: 'g-002',
        name: 'Charity Digital Transformation Grant',
        agency: 'GovTech',
        description: 'Supports charities in adopting digital solutions to improve operational efficiency.',
        quantum: '80% support capped at $30,000',
        deadline: '2026-03-31',
        sectors: ['Social Service', 'Arts & Heritage', 'Sports', 'Community', 'Education', 'Health', 'Environment'],
        eligibility: ['Registered Charity', 'IPC Status'],
    },
    {
        id: 'g-003',
        name: 'Arts Creation Fund',
        agency: 'NAC',
        description: 'Supports the creation, development and presentation of new original works.',
        quantum: 'Up to $50,000',
        deadline: '2026-04-15',
        sectors: ['Arts & Heritage'],
        eligibility: ['Singaporean/PR', 'Registered Arts Group'],
    },
    {
        id: 'g-004',
        name: 'Community Sports Fund',
        agency: 'SportSG',
        description: 'Encourages the community to initiate and organize grassroots sport initiatives.',
        quantum: 'Up to $20,000',
        deadline: 'Rolling',
        sectors: ['Sports', 'Community'],
        eligibility: ['Community Group', 'Interest Group'],
    },
    {
        id: 'g-005',
        name: 'Our Singapore Fund',
        agency: 'MCCY',
        description: 'Supports projects that build national identity and meet community needs.',
        quantum: 'Up to $20,000 or 80% of expenditure',
        deadline: '2026-12-31',
        sectors: ['Community', 'Arts & Heritage', 'Social Service'],
        eligibility: ['Open to all', 'Ground-up Initiative'],
    },
    {
        id: 'g-006',
        name: 'Environmental Edu Grant',
        agency: 'MSE',
        description: 'For projects that educate the public on environmental issues.',
        quantum: '$5,000 - $50,000',
        deadline: '2026-09-01',
        sectors: ['Environment', 'Education'],
        eligibility: ['Schools', 'NGOs'],
    },
];
