import type { Grant } from './types';

export const GRANTS_DATA: Grant[] = [
    {
        id: 'g-001',
        name: 'VWO Capability Fund',
        agency: 'NCSS',
        description: 'Provides funding for VWOs to strengthen their governance and management capabilities.',
        quantum: 'Up to $100,000',
        deadline: '2026-06-30',
        sectors: ['Social Service', 'Health', 'Community'],
        eligibility: ['Registered Charity', 'IPC Status', 'Member of NCSS'],
    },
    {
        id: 'g-002',
        name: 'Charity Digital Transformation Grant',
        agency: 'GovTech',
        description: 'Supports charities in adopting digital solutions to improve operational efficiency.',
        quantum: '80% support capped at $30,000',
        deadline: '2026-03-31',
        sectors: ['Social Service', 'Arts & Heritage', 'Sports', 'Community', 'Education', 'Health', 'Environment'],
        eligibility: ['Registered Charity', 'IPC Status'],
    },
    {
        id: 'g-003',
        name: 'Arts Creation Fund',
        agency: 'NAC',
        description: 'Supports the creation, development and presentation of new original works.',
        quantum: 'Up to $50,000',
        deadline: '2026-04-15',
        sectors: ['Arts & Heritage'],
        eligibility: ['Singaporean/PR', 'Registered Arts Group'],
    },
    {
        id: 'g-004',
        name: 'Community Sports Fund',
        agency: 'SportSG',
        description: 'Encourages the community to initiate and organize grassroots sport initiatives.',
        quantum: 'Up to $20,000',
        deadline: 'Rolling',
        sectors: ['Sports', 'Community'],
        eligibility: ['Community Group', 'Interest Group'],
    },
    {
        id: 'g-005',
        name: 'Our Singapore Fund',
        agency: 'MCCY',
        description: 'Supports projects that build national identity and meet community needs.',
        quantum: 'Up to $20,000 or 80% of expenditure',
        deadline: '2026-12-31',
        sectors: ['Community', 'Arts & Heritage', 'Social Service'],
        eligibility: ['Open to all', 'Ground-up Initiative'],
    },
    {
        id: 'g-006',
        name: 'Environmental Edu Grant',
        agency: 'MSE',
        description: 'For projects that educate the public on environmental issues.',
        quantum: '$5,000 - $50,000',
        deadline: '2026-09-01',
        sectors: ['Environment', 'Education'],
        eligibility: ['Schools', 'NGOs'],
    },
    {
        id: 'g-007',
        name: 'Arts Digital Presentation Grant',
        agency: 'NAC',
        description: 'Supports the presentation of arts content in digital formats.',
        quantum: 'Up to $20,000',
        deadline: '2026-05-30',
        sectors: ['Arts & Heritage'],
        eligibility: ['Arts Groups', 'Individual Artists'],
    },
    {
        id: 'g-008',
        name: 'Seniors Go Digital Fund',
        agency: 'IMDA',
        description: 'Projects that help seniors adopt digital technology for daily living.',
        quantum: 'Up to $50,000',
        deadline: '2026-08-15',
        sectors: ['Community', 'Social Service'],
        eligibility: ['VWOs', 'Community Clubs'],
    },
    {
        id: 'g-009',
        name: 'SG Eco Fund',
        agency: 'MSE',
        description: 'For ground-up projects that advance environmental sustainability.',
        quantum: 'Up to $50,000',
        deadline: '2026-10-01',
        sectors: ['Environment', 'Community'],
        eligibility: ['Open to all'],
    },
    {
        id: 'g-010',
        name: 'Tech for Good Initiative',
        agency: 'GovTech',
        description: 'Co-funding for tech solutions that solve social problems.',
        quantum: 'Up to $100,000',
        deadline: 'Rolling',
        sectors: ['Social Service', 'Community', 'Health'],
        eligibility: ['Registered Charities', 'Social Enterprises'],
    },
    {
        id: 'g-011',
        name: 'Youth Sports Development',
        agency: 'SportSG',
        description: 'Funding for youth-centric sports programs and academies.',
        quantum: 'Up to $25,000',
        deadline: '2026-04-01',
        sectors: ['Sports', 'Education'],
        eligibility: ['Sports Clubs', 'Schools'],
    },
    {
        id: 'g-012',
        name: 'Heritage Awareness Grant',
        agency: 'NHB',
        description: 'Promoting awareness and appreciation of Singapore\'s heritage.',
        quantum: 'Up to $15,000',
        deadline: '2026-07-20',
        sectors: ['Arts & Heritage', 'Education', 'Community'],
        eligibility: ['Individuals', 'Non-Profits'],
    },
];
